# Generated by Django 5.2.1 on 2025-05-28 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness', models.CharField(choices=[('diabetes', 'Сахарный диабет'), ('celiac', 'Целиакия'), ('phenylketonuria', 'Фенилкетонурия'), ('lactose', 'Непереносимость лактозы'), ('none', 'Нет заболеваний')], default='none', max_length=50, verbose_name='Заболевание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
