# Generated by Django 5.2.1 on 2025-05-28 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(default=170, help_text='Введите ваш рост в сантиметрах', validators=[django.core.validators.MinValueValidator(100, message='Рост не может быть меньше 100 см'), django.core.validators.MaxValueValidator(250, message='Рост не может быть больше 250 см')], verbose_name='Рост (см)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=70.0, help_text='Введите ваш вес в килограммах', max_digits=5, validators=[django.core.validators.MinValueValidator(30, message='Вес не может быть меньше 30 кг'), django.core.validators.MaxValueValidator(300, message='Вес не может быть больше 300 кг')], verbose_name='Вес (кг)'),
        ),
    ]
