# Generated by Django 5.2.1 on 2025-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_height_userprofile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
