# Generated by Django 5.2.1 on 2025-06-26 00:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('height', models.PositiveIntegerField(default=170, help_text='Введите рост в сантиметрах', validators=[django.core.validators.MinValueValidator(100, message='Рост не может быть меньше 100 см'), django.core.validators.MaxValueValidator(250, message='Рост не может быть больше 250 см')], verbose_name='Рост (см)')),
                ('weight', models.DecimalField(decimal_places=1, default=70.0, help_text='Введите вес в килограммах', max_digits=5, validators=[django.core.validators.MinValueValidator(30, message='Вес не может быть меньше 30 кг'), django.core.validators.MaxValueValidator(300, message='Вес не может быть больше 300 кг')], verbose_name='Вес (кг)')),
                ('sickness', models.CharField(choices=[('diabetes', 'Сахарный диабет'), ('celiac', 'Целиакия'), ('phenylketonuria', 'Фенилкетонурия'), ('lactose', 'Непереносимость лактозы'), ('none', 'Нет заболеваний')], default='none', max_length=50, verbose_name='Заболевание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карточка пользователя',
                'verbose_name_plural': 'Карточки пользователей',
            },
        ),
    ]
